databases:
  - name: budget-app
    databaseName: budget_app_q84n
    user: budget_app_q84n_user

services:
  - type: web
    name: budget app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_q84n
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false